apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260524-004610-zr3gga7wdcb9-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260524-004610-zr3gga7wdcb9.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260524-004610-zr3gga7wdcb9-service
            port:
              number: 80
