apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260524-004610-zr3gga7wdcb9-service
spec:
  selector:
    app: enterprise-system-20260524-004610-zr3gga7wdcb9
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
